FROM almalinux
ENV course="devops"\
    trainer="surya"
ARG duration="120hrs"

RUN echo "Hi, I am learning ${course} under the guidence of ${trainer} having session of ${duration}"

CMD ["sleep" "1000"]

# TO chcek the echo we have to login to the container, we can login to the active instance only so to make contianer active state we assigned one taks to it that is sleepoing